language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3

matrix:
  fast_finish: true

before_install:
  - sh -c 'echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer config "platform.ext-mongo" "1.6.16" && composer update $COMPOSER_FLAGS --prefer-dist

script: if [[ "$TRAVIS_PHP_VERSION" == "7.2" && -z "$SYMFONY_VERSION" && -z "$COMPOSER_FLAGS" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
